version: '3.8'
services:
  document:
    container_name: bakerdh/testactionsmarkdown:knit
    image: bakerdh/testactionsmarkdown:knit
    volumes:
      - .:/home/rstudio
    environment:
      DISABLE_AUTH: 'true'
    working_dir: /home/rstudio
    command: make document-docker
